const APPLICATION_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  LOGIN: "LOGIN",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  DISBURSED: "DISBURSED",
  CANCELLED: "CANCELLED",
};

const APPLICATION_TRANSITIONS = {
  DRAFT: ["SUBMITTED", "CANCELLED"],

  SUBMITTED: ["LOGIN", "REJECTED", "CANCELLED"],

  LOGIN: ["APPROVED", "REJECTED"],

  APPROVED: ["DISBURSED", "REJECTED"],

  REJECTED: [],

  DISBURSED: [],

  CANCELLED: [],
};

module.exports = {
  APPLICATION_STATUS,
  APPLICATION_TRANSITIONS,
};